### PR TITLE
vector

### PR DESCRIPTION
**Pull request by ScottSWu**
🎆 awesome start!

Unfortunately we can't seem to comment on repository code, only on PRs.
- I would propose a vector over a list. We won't be modifying list after initializing it, and other than insertions a vector is more performant.
- gcc wanted a default constructor - hopefully that doesn't affect the visual studio compiler
- Is job queue only taking jobs through a network service? could we sometimes hard code jobs for tests or load them from a file?

### CODE REVIEW

**Comment by ofp3** [comment]
Looks good. For your third point, I suppose we could have one of the main arguments as a file for a "test job queue" that will be specified when testing and used instead of the network service. Or did you want us to accommodate both a job queue file and the network interface during the same run of the program? That might be a more difficult task.

**Comment by ScottSWu** [comment]
Perhaps the latter - something like

```
JobQueue q;

onNetworkRequest(data) {
    q.addJob(data);
}

main() {
    if (jobFileArg)
        q.addJob(jobFile);
}
```

**Comment by ofp3** [comment]
Ah ok. Are we assuming that jobFile contains one job only, or treating it as a newline separated list of jobs?

**Comment by ScottSWu** [comment]
A newline separated list sounds good.

If you change the job queue interface for that, I could start on jobs received over the network.

**Comment by ofp3** [comment]
Will do. Gonna merge this pull request so I can fork and modify the job queue.

**Pull request merged**
